name: Build application

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
         submodules: recursive

    - name: Build the Docker image
      run: ./build-container.sh

    - name: Build the application
      run: ./build-app.sh

    - name: Archive the product
      uses: actions/upload-artifact@v4
      with:
              name: clockapp-${{ github.ref_name }}
              path: src/build/clockapp
